apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-media
  labels:
    type: nfs
spec:
  capacity:
    storage: MEDIA_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_SERVER_IP
    path: MEDIA_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: MEDIA_STORAGE_SIZE
