apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-redis
  labels:
    type: nfs
spec:
  capacity:
    storage: REDIS_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_SERVER_IP
    path: REDIS_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-redis
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: REDIS_STORAGE_SIZE
