apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cdcs-django
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.cdcs.replicas }}
  selector:
    matchLabels:
      component: cdcs-django
  template:
    metadata:
      labels:
        component: cdcs-django
    spec:
      containers:
      - name: nginx-sidecar
        image: {{ .Values.cdcs.sidecar.image }}:{{ .Values.cdcs.sidecar.tag }}
        imagePullPolicy: {{ .Values.cdcs.sidecar.imagePullPolicy }}
        securityContext:
          {{- toYaml .Values.cdcs.sidecar.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.cdcs.sidecar.resources | nindent 10 }}
        ports:
            - name: http
              containerPort: 80
              protocol: TCP
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-default-template-conf
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
              readOnly: true
            - name: staticfiles
              mountPath: /srv/curator_static
              readOnly: true
      - image: {{ .Values.cdcs.image }}:{{ .Values.cdcs.tag }}
        imagePullPolicy: {{ .Values.cdcs.imagePullPolicy }}
        securityContext:
          {{- toYaml .Values.cdcs.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.cdcs.resources | nindent 10 }}
        name: cdcs
        {{- if .Values.cdcs.celery.startService }}
        command:
        - "/docker-entrypoint-django.sh"
        {{- end }}
        args: ["$(PROJECT_NAME)", "gunicorn"]
        env:
        {{- range .Values.cdcs.envs }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ tpl (.Values.cdcs.secret.name) . }}"
              key: django_secret_key
        {{- if .Values.postgresql.enabled }}
        {{- with .Values.postgresql }}
        - name: POSTGRES_HOST
          value: "{{ .service.name }}"
        - name: POSTGRES_PORT
          value: "{{ .service.port }}"
        - name: POSTGRES_DB
        {{- if and .auth.existingSecret .auth.secretKeys.databaseKey }}
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{.auth.secretKeys.databaseKey}}"
        {{- else }}
          value: "{{.auth.database}}"
        {{- end }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{.auth.secretKeys.usernameKey}}"
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{.auth.secretKeys.passwordKey}}"
        {{- if eq .architecture "replication" }}
        - name: POSTGRES_REPLICA_HOST
          value: "{{ .readReplicas.service.name }}"
        - name: POSTGRES_REPLICA_PORT
          value: "{{ .readReplicas.service.port }}"
        - name: POSTGRES_REPLICA_DB
        {{- if and .auth.existingSecret .auth.secretKeys.databaseKey }}
        valueFrom:
          secretKeyRef:
            name: "{{.auth.existingSecret}}"
            key: "{{.auth.secretKeys.databaseKey}}"
        {{- else }}
        value: "{{.auth.database}}"
        {{- end }}
        - name: POSTGRES_REPLICA_USER
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{.auth.secretKeys.usernameKey}}"
        - name: POSTGRES_REPLICA_PASS
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{.auth.secretKeys.passwordKey}}"
        {{- end }} # end if replication
        {{- end }} # end with postgresql
        {{- end }} # end if postgresql
        {{- if .Values.mongodb.enabled }}
        {{- with .Values.mongodb }}
        - name: MONGO_HOST
          value: "{{ .service.name }}"
        - name: MONGO_PORT
          value: "{{ .service.port }}"
        - name: MONGO_DB
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{ .auth.secretKeys.databaseKey }}"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{ .auth.secretKeys.usernameKey }}"
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{ .auth.secretKeys.passwordKey }}"
        {{- end }} # end with mongodb
        {{- end }} # end if mongodb
        {{- if .Values.redis.enabled }}
        {{- with .Values.redis }}
        - name: REDIS_HOST
          value: "{{ .service.name }}"
        - name: REDIS_PORT
          value: "{{ .service.port }}"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: "{{.auth.existingSecret}}"
              key: "{{ .auth.secretKeys.passwordKey }}"
        {{- end }} # end with redis
        {{- end }} # end if redis
        - name: DJANGO_SETTINGS_MODULE
          value: "$(PROJECT_NAME).$(SETTINGS)"
        ports:
        - containerPort: 8000
        volumeMounts:
            - name: staticfiles
              mountPath: /srv/curator/static.prod
            - name: mediafiles
              mountPath: /srv/curator/media
      volumes:
        - name: nginx-conf
          configMap:
            name: "{{ .Release.Name }}-cdcs-nginx-conf"
        - name: nginx-default-template-conf
          configMap:
            name: "{{ .Release.Name }}-cdcs-nginx-default-template-conf"
        - name: staticfiles
          emptyDir: {}
        {{- if .Values.cdcs.persistence.media.existingClaim }}
        - name: mediafiles
          persistentVolumeClaim:
            claimName: "{{ .Values.cdcs.persistence.media.existingClaim }}"
        {{- else }}
        - name: mediafiles
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-cdcs-pvc-media"
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      {{- with .Values.cdcs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cdcs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cdcs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}