{{- if .Values.postgresqlha.postgresql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl (.Values.postgresqlha.postgresql.secret.name) . }}"
  namespace: {{ .Release.Namespace }}
type: generic
stringData:
  username: {{ .Values.postgresqlha.postgresql.username }}
  database: {{ .Values.postgresqlha.postgresql.database }}
  password: {{ .Values.postgresqlha.postgresql.secret.password }}
  postgres-password: {{ .Values.postgresqlha.postgresql.secret.postgresPassword }}
  repmgr-password: {{ .Values.postgresqlha.postgresql.secret.repmgrPassword }}
{{- end }}