{{- if .Values.postgresqlha.pgpool.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl (.Values.postgresqlha.pgpool.secret.name) . }}"
  namespace: {{ .Release.Namespace }}
type: generic
stringData:
  admin-password: {{ .Values.postgresqlha.pgpool.secret.adminPassword }}
{{- end }}