apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-media
  labels:
    type: local
spec:
  capacity:
    storage: MEDIA_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  hostPath:
    path: MEDIA_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: cdcs-pv-media
  resources:
    requests:
      storage: MEDIA_STORAGE_SIZE

