apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-mongo
  labels:
    type: local
spec:
  capacity:
    storage: MONGO_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  hostPath:
    path: MONGO_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-mongo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: cdcs-pv-mongo
  resources:
    requests:
      storage: MONGO_STORAGE_SIZE

