apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-postgres
  labels:
    type: local
spec:
  capacity:
    storage: POSTGRES_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  hostPath:
    path: POSTGRES_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-postgres
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: cdcs-pv-postgres
  resources:
    requests:
      storage: POSTGRES_STORAGE_SIZE

