apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdcs-pv-redis
  labels:
    type: local
spec:
  capacity:
    storage: REDIS_STORAGE_SIZE
  accessModes:
    - ReadWriteMany
  hostPath:
    path: REDIS_VOLUME_PATH
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdcs-pvc-redis
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: cdcs-pv-redis
  resources:
    requests:
      storage: REDIS_STORAGE_SIZE

